bedroom_lights:
  name: Bedroom Lights Automation
  icon: mdi:bed
  initial: true

office_lights:
  name: Office Light Automation
  icon: mdi:lightbulb-on
  initial: true

security:
  name: Security
  icon: mdi:lock
  initial: false
