- platform: template
  sensors:
    battery_iphone:
      friendly_name: iPhone Battery
      unit_of_measurement: '%'
      value_template: >-
          {%- if state_attr('device_tracker.iphone', 'battery') %}
              {{ state_attr('device_tracker.iphone', 'battery')|round }}
          {% else %}
              {{ states('sensor.battery_iphone') }}
          {%- endif %}
      device_class: battery