# CPU Temperature
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
  
  # GPU Temperature
- platform: command_line
  name: GPU Temperature
  command: "/opt/vc/bin/vcgencmd measure_temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | replace("temp=", "") | replace("''C", "") }}'

- platform: version
  name: Hassio Version

#- platform: scrape
#  resource: https://www.home-assistant.io
#  name: Release
#  select: ".current-version h1"
#  value_template: '{{ value.split(":")[1] }}'

- platform: uptime
  name: Time Online
  unit_of_measurement: hours