- platform: synologydsm
  host: !secret syn_ip
  username: !secret syn_un
  password: !secret syn_pw
  monitored_conditions:
#    - cpu_1min_load
#    - cpu_5min_load
#    - cpu_15min_load
#    - cpu_system_load
#    - cpu_total_load
#    - cpu_user_load
    - disk_below_remain_life_thr
    - disk_exceed_bad_sector_thr
    - disk_smart_status
#    - disk_temp
#    - memory_available_real
#    - memory_cached
#    - memory_real_usage
#    - memory_total_real
    - network_up
    - network_down
    - volume_percentage_used
    - volume_size_total
    - volume_size_used
#    - volume_status