purge_interval: 1
purge_keep_days: 5
exclude:
  domains:
    - automation
    - script
    - weblink
    - updater
  entities:
    - sensor.date
    - sensor.date_time
    - sensor.time
    - sensor.time_date
    - sun.sun