# ███████╗ ██████╗ ███╗   ██╗███████╗███████╗
# ╚══███╔╝██╔═══██╗████╗  ██║██╔════╝██╔════╝
#   ███╔╝ ██║   ██║██╔██╗ ██║█████╗  ███████╗
 # ███╔╝  ██║   ██║██║╚██╗██║██╔══╝  ╚════██║
# ███████╗╚██████╔╝██║ ╚████║███████╗███████║
# ╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚══════╝

- name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  radius: 300
  icon: mdi:home

- name: Office
  latitude: !secret office_lat
  longitude: !secret office_long
  radius: 200
  icon: mdi:office